#!/bin/sh
#
# snowflake script.
#
# Snowflake, and all new java services, require the same directory structure
#   /usr/local/share/megamsnowflake should contain 'releases' directory and be able to create a symlink
#   /var/log/snowflake (chown daemon, chmod 775)

APP_NAME="snowflake"
MAIN_JAR="snowflake-1.0.2-SNAPSHOT.jar"
VERSION="1.0.2-SNAPSHOT"
SNOWFLAKE_HOME="$(cd "$(cd "$(dirname "$0")"; pwd -P)"/..; pwd)"

MAIN_CLASS="com.twitter.service.snowflake.SnowflakeServer"
SNOWFLAKE_CLASSPATH="$AKKA_HOME/config:$AKKA_HOME/lib/*"

HEAP_OPTS="-Xmx700m -Xms700m -Xmn500m"
JMX_OPTS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"
GC_OPTS="-XX:+UseConcMarkSweepGC -verbosegc -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCDateStamps -XX:+UseParNewGC -Xloggc:/var/log/snowflake/gc.log"
DEBUG_OPTS="-XX:ErrorFile=/var/log/$APP_NAME/java_error%p.log"
JAVA_OPTS="-server $GC_OPTS $JMX_OPTS $HEAP_OPTS $DEBUG_OPTS"

echo $SNOWFLAKE_HOME

java ${JAVA_OPTS} -cp ${SNOWFLAKE_HOME}/${MAIN_JAR} ${MAIN_CLASS} -f ${SNOWFLAKE_HOME}/config/$1